# Generated by Django 3.2 on 2023-11-15 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichmentDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('taxonomy', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ProvisionEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provision_id', models.CharField(max_length=512)),
                ('taxonomy_topic', models.CharField(max_length=1024)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichments', to='reader.enrichmentdataset')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichments', to='reader.work')),
            ],
        ),
    ]
